### ISSUE TITLE
Account Swith Bug

### ISSUE THREAD

**Issue by Xle6yWek** [l0c4lh057/AccountSwitcher#13]
**Describe the bug**
Just leave a account when swith key is pressed

**To Reproduce**
1. Go to plugin settings
2. Add two accounts
3. Press switch key

**Expected behavior**
Swith accounts

**Information (please complete the following information):**
 - OS: Windows 10
 - Plugin Version: 1.2.6
 - Discord version: Stable
 - Compact Mode enabled? no

**Comment by l0c4lh057** [comment]
Do you have encryption enabled?

**Comment by Xle6yWek** [comment]
Yes

**Comment by l0c4lh057** [comment]
Probably related to #14, I'd rather keep the discussion about it there.
