### ISSUE TITLE
[Request] reloading plugins when switching accounts

### ISSUE THREAD

**Issue by Xenorio** [l0c4lh057/AccountSwitcher#16]
**Is your feature request related to a problem? Please describe.**
Switching accounts breaks some other plugins which means you have to manually reload them every time. For example AutoStartRichPresence by Mega_Mewthree

**Describe the solution you'd like**
Having a configurable list of plugins that are reloaded on every account switch would solve any problems with them while not needlessly reloading non-affected plugins

**Describe alternatives you've considered**
An easier solution would be to just always reload every plugin, but that would have a big impact on performance for no reason

**Additional context**
No additional context needed

**Comment by l0c4lh057** [comment]
I already added this for AccountDetailsPlus (dunno if it was before or after the rewrite though) but this is a good idea. I'll take care of that with a custom list with some plugins as default. If someone knows more plugins with this issue feel free to add them in the comments here.
* AutoStartRichPresence
* AccountDetailsPlus

**Comment by Xenorio** [comment]
closing because it has been added. well done, works great!
