### ISSUE TITLE
[Request] Use multiple accounts at the same time

### ISSUE THREAD

**Issue by Huddlect** [l0c4lh057/AccountSwitcher#17]
**Is your feature request related to a problem? Please describe.**
I use different accounts for different kinds of guilds. For example I have a school account and a private account. Therefore I always have to switch between the accounts to check for new messages.

**Describe the solution you'd like**
I would like to see the guilds all my accounts are a member of and whether there are new messages in the guild at the same time in the guild list and automatically switch to the corresponding account when opening the server.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by l0c4lh057** [comment]
It is not like I did not consider this in the past. This is one of my early ideas I had but sadly discords self bot protection makes it pretty hard to do. I know that some discord bot libraries can control user accounts but to do that with a plugin I think I'd need to implement everything on my own. An alternative would be to create a new websocket connection with the other account but I could not find out how to access the websocket. When I have more information that would make it possible for me to do that I will definitely consider doing it, but at the moment that won't happen.

**Comment by Huddlect** [comment]
Thanks for the quick response.

**Comment by Huddlect** [comment]
Would it be possible to just add the guilds to the list without them being updated and only switch to the corresponding account when selecting a guild?

**Comment by l0c4lh057** [comment]
That's the first thing I tried to do but the `/guilds` endpoint used to get all guilds you are member of is only available for bot accounts. The guilds get sent to the client when initializing the connection but that would require a websocket again.

**Comment by Huddlect** [comment]
Kk too bad. Thanks again for the quick and pleasant exchange though.
