### ISSUE TITLE
[Issue] Failed to start AccountSwitcher

### ISSUE THREAD

**Issue by blackbracken** [l0c4lh057/AccountSwitcher#19]
**Describe the bug**
On starting discord, it showed `AccountSwitcher v1.2.11 has been started` but didn't `AccountSwitcher v1.2.11 has been enabled`.

**To Reproduce**
1. Start discord or reload the plugin.

**Screenshots**
screenshot when enabling AccountSwitcher
![cap](https://user-images.githubusercontent.com/18373318/87506890-59674680-c6a7-11ea-98eb-a6accce8de9f.png)

**Information (please complete the following information):**
 - OS: [Windows 10]
 - Plugin Version: [1.2.11]
 - Discord version: [Stable]
 - Compact Mode enabled? [no]
 - Encryption enabled? [no]

**Comment by l0c4lh057** [comment]
Download the ZeresPluginLibrary plugin which can be found here: https://betterdiscord.net/ghdl?id=2252
