### ISSUE TITLE
[Issue] Settings panel of plugin inaccessible using BandagedBD v1.0.5

### ISSUE THREAD

**Issue by DudeManGuy0** [l0c4lh057/AccountSwitcher#20]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
When attempted to access the settings panel for the plugin in Bandaged BD settings by pressing the settings button on the plugin, this happens:
![image](https://user-images.githubusercontent.com/50563358/89738887-59a1fa00-da39-11ea-89c8-217928d07875.png)
![image](https://user-images.githubusercontent.com/50563358/89738891-60307180-da39-11ea-8e09-bf30ed7c9109.png)

**To Reproduce**
1. Install Bandaged BD v1.05
2. Access settings of the plugin by going to Discord settings -> Plugins -> AccountSwitcher -> Settings

**Expected behavior**
The settings menu showing up and allowing for user input

**Console menu/Traceback**
![image](https://user-images.githubusercontent.com/50563358/89738954-ed73c600-da39-11ea-86c8-f2e31bd79cfc.png)

**Information which may have to do with it**
These errors I was getting from ZLibrary itself above in the console.
![image](https://user-images.githubusercontent.com/50563358/89738972-15fbc000-da3a-11ea-8b16-8159170c143e.png)

**Information (please complete the following information):**
 - OS:  Windows 10
 - Plugin Version: Latest as of this post
 - Discord version: Stable BandagedBD
 - Compact Mode enabled? no
 - Encryption enabled? no

**Comment by l0c4lh057** [comment]
**﻿If AccountSwitcher is not working for you﻿** you probably don't have the local version of the library installed. It is a plugin which you can download here: https://betterdiscord.net/ghdl?id=2252﻿.
