### ISSUE TITLE
Setting won't display.

### ISSUE THREAD

**Issue by DaneelAndGiskard** [l0c4lh057/AccountSwitcher#21]
Putting the folder in the plugin folder -> not detected

Putting only the .js -> Startup but can't enter the settings, and can't be stopped

Putting the whole content of the folder at the root of the plugin folder -> same as only putting the .js

**Comment by l0c4lh057** [comment]
﻿If AccountSwitcher is not working for you﻿ you probably don't have the local version of the library installed. It is a plugin which you can download here: https://betterdiscord.net/ghdl?id=2252﻿.

After downloading that plugin restart discord and it should work.

**Comment by DaneelAndGiskard** [comment]
Works fine, thx!
