### ISSUE TITLE
[Issue] Disabling encrypt tokens doesnt work

### ISSUE THREAD

**Issue by Motzumoto** [l0c4lh057/AccountSwitcher#22]
When i disable the encrypt tokens button it doesnt decrypt them or anything, sometimes i use the account switcher as an easy way to get my token if i ever need it, and it being encrypted isnt helping

**Comment by l0c4lh057** [comment]
That is not a bug, it is intended. Otherwise people could just paste in some arbitrary token and they could log in with that. That's why tokens are encrypted even if encryption is disabled.

**Comment by Motzumoto** [comment]
> I do not support people logging in to accounts they do not own which is why you need to be logged in in order to save an account. The token is encrypted to make sure nobody just pastes another token in the config file.
> 
> I also don't think you should ever do something you need your plain text token for. The user should never even see the token and if you need to have it then I don't think you should do whatever you are doing.
> 
> Feel free to read the source code and find out how to do it, it is only a single line of code you need, but I won't help with that.

I literally fucking said i use it on my OWN accounts to get my tokens.

**Comment by l0c4lh057** [comment]
An I told you why I decided to encrypt tokens even if encryption is disabled. While YOU might not do anything malicious, other people would. You are not the only person using the plugin. Also getting showing you your own token is not what the plugin is supposed to do.

But again:
> Feel free to read the source code and find out how to do it, it is only a single line of code you need, but I won't help with that.

**Comment by Motzumoto** [comment]
And you dont need to know what im doing with my own tokens, if i need them, i need them, thats none of your concern
