### ISSUE TITLE
[Issue] Logs me out on 2FA Account

### ISSUE THREAD

**Issue by mirandazellnik** [l0c4lh057/AccountSwitcher#27]
I've added two accounts, one of which has 2FA enabled. When I switch from that account to another, non-2FA account all is well. But when I then switch back, I find myself on a login page, where I must re-sign in to my main, 2FA account, in order to access it.

1. Sign in to a 2FA-enabled account
2. Go to plugin settings, and add the account
3. Hit sign out
4. Sign into another, non-2FA account
5. Go to plugin settings, and add the account
6. Perform the shortcut to go back to the first account
7. Now I'm on a login screen - I've been logged out of the first account
8. Sign back in to it, complete 2FA, all that stuff
9. Switch to 2nd account - works fine
10. Switch back to first - I'm logged out again. Go back to step 7.

 - OS: Ubuntu
 - Plugin Version: 1.3.2
 - Discord version: Normal
 - Compact Mode enabled? No
 - Encryption enabled? Same happens both ways

**Comment by l0c4lh057** [comment]
Please check #14 on this problem, it has some information that might be useful. There also is [a guide how to maybe fix this](https://github.com/l0c4lh057/AccountSwitcher/issues/14#issuecomment-779875799) that you can give a try.
