### ISSUE TITLE
[Request] Check all accounts when clicking a discord jump link

### ISSUE THREAD

**Issue by Chew** [l0c4lh057/AccountSwitcher#28]
I usually hate when people remove templates, but the default one for feature requests is garbage, and I can describe it better without.

When clicking on a Jump URL, sometimes the currently signed-in user doesn't have access to view it. If they don't, they get an error like this: 
![image](https://user-images.githubusercontent.com/8278263/108463404-f395fb00-7243-11eb-95d9-ca46abf5cdf4.png)

If this happens, it should cycle through the different accounts until one returns a proper response and then jumps that channel on the specified account.

Just an idea that would help me a lot. I have an account for work I need to switch back and forth between, and sometimes I like to link to channels I can't access on my main account. This would save a little bit of time!

**Comment by l0c4lh057** [comment]
To check automatically which account has access would require a connection to discord which I really do not want to do, that could easily get flagged for being a selfbot, or it would require quite some storage space to save all channel ids for every account and then it might not even be correct anymore, maybe you left the sever or got kicked. And just trying with every account is definitely not something I would do, first bc there might not be a single account and secondly bc that is a very bad solution to this problem.

**Comment by Chew** [comment]
What about right-clicking jump URL, Jump to as > Account names? This is essentially the same effect minus all the unnecessary stuff.
