### ISSUE TITLE
[Request] Toggle Accounts with Mouse

### ISSUE THREAD

**Issue by C0D3-M4513R** [l0c4lh057/AccountSwitcher#29]
**Is your feature request related to a problem? Please describe.**
I have a Problem, where this AccountSwitcher won't work with a third party discord application, because of a broken feature (Different Discord tabs). This causes Key Combinations to be detected in the settings, but not actually, when using Discord. 

**Describe the solution you'd like**
I would like for you to add a button to the Plugin Settings, next to each account, to 'manually' switch accounts.

**Describe alternatives you've considered**
Using multiple isolated discord versions. 
eg. Like having Discord, Discord-PTB and Discord-Canary installed parralell, each with a different account

**Comment by l0c4lh057** [comment]
When you use the mouse wheel to click on your avatar in the panel with the mute/deafen/settings icon then it should open up a panel in which you can then select accounts to switch to ([as stated in the readme](https://github.com/l0c4lh057/AccountSwitcher#switching-accounts)). You can also change the keybind to switch in the plugin settings to use something else.

**Comment by sitiom** [comment]
@l0c4lh057 Is it just me that even though I middle clicked everything in the panel nothing pops up? I'm not using any theme btw

**Comment by C0D3-M4513R** [comment]
For me middle clicking works. I’ll have to check, where I’ve gotta click.

**Comment by sitiom** [comment]
Oh thanks, turns out I had [RadialStatus](https://betterdiscordlibrary.com/themes/RadialStatus) theme turned on. What a bummer.

**Comment by l0c4lh057** [comment]
Nice that you found out what is causing the issue. I can try to find a solution, maybe attaching the listener to that element too. Can you maybe enable the theme, then open the console (ctrl+shift+i), then click the button in image 1 which should be in the upper left corner of the devtools, and then hover over your avatar and just click. It should then highlight an element in the `Elements` tab of the devtools, you can see which one it is for me in image 2. Then post the image of the element it highlighted for you, I guess it will be something else.

image 1:
![grafik](https://user-images.githubusercontent.com/42084688/110787379-89cea700-826d-11eb-80de-4b36f5e4911c.png)

image 2:
![grafik](https://user-images.githubusercontent.com/42084688/110787621-de722200-826d-11eb-9be2-d4219be5bc85.png)

**Comment by sitiom** [comment]
Yes it is.
![image](https://user-images.githubusercontent.com/56180050/110788298-69244280-82a9-11eb-823e-477fc3e00b20.png)
