### ISSUE TITLE
[Request] Focus on password textbox when switching and allow enter

### ISSUE THREAD

**Issue by sitiom** [l0c4lh057/AccountSwitcher#33]
That said, it is inconvenient to reach over my mouse everytime to select the textbox and pressing the `Okay` button.

**Comment by ezeholz** [comment]
I agree with you, and I'm working on a solution for that.
Right now, I'm able to write as soon as the input shows. I'm trying to set the enter key to work with the "Okay" button. As soon as that works, I'll PR the changes.
Cheers :D
