### ISSUE TITLE
[Issue] Account switching not working

### ISSUE THREAD

**Issue by C0D3-M4513R** [l0c4lh057/AccountSwitcher#35]
**Describe the bug**
I updated BandagedBD, because the Injector changed.
After the update, I can't switch accounts with UI elements, and assigned Keybinds.

**To Reproduce**
1.  Verify, that the following versions are at least installed: 

> BD 1.0.0 (stable)
> Host 0.0.309 (What is this? is this relevant?)
> Injector 0.6.0

2. Try to Switch Accounts. Nothing happens.
3. Try to Switch to the same account. A warning appears, that you can't switch to the account, that you are using.

**Expected behavior**

**Screenshots**
Please also check the console by pressing `Ctrl + Shift + I` (`Cmd + Shift + I` on MacOS) and send screenshots of errors (red messages)

**Information (please complete the following information):**
 - OS: Windows 10
 - Plugin Version: v.1.2.3
 - Discord version: Stable
 - Compact Mode enabled? no
 - Encryption enabled? no

**Comment by ogoidmatos** [comment]
I too have been experiencing this issue since updating BD. I have the exact same issue has described above.
Also, besides not being able to change accounts, it is not possible to add them.

**Comment by fionamorrison13** [comment]
+1

**Comment by C0D3-M4513R** [comment]
> Also, besides not being able to change accounts, it is not possible to add them.

Will test later. Wait for edit.

**Comment by C0D3-M4513R** [comment]
Possibly, this has something to do with added security features, in that update.

**Comment by C0D3-M4513R** [comment]
So funny thing: I just successfully added an account, and switching works.
There are 2 installers i think.
https://github.com/rauenzi/BetterDiscordApp/releases and
https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-beta
It probably depends, on the installer used. I know, that I reinstalled Better Discord with the installer from https://github.com/BetterDiscord/Installer/releases/tag/v1.0.0-beta.
My Discord Installation also says: 
> BetterDiscord 1.1.0
Host 1.0.9001

**Comment by C0D3-M4513R** [comment]
Didn't realize, that this issue still existed. Have been using this account switcher for a while without problems.
There probably exists some issue with some installer.
Closing.
