### ISSUE TITLE
[Issue] very short issue description

### ISSUE THREAD

**Issue by Aiden-Wright** [l0c4lh057/AccountSwitcher#42]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
Signs out of account when switching

**To Reproduce**
Switch between accounts

**Expected behavior**
It switches between the two accounts and doesn't require repeated sign ins. 

**Information (please complete the following information):**
 - OS: Windows
 - Plugin Version: 4b10661
 - Discord version: BetterDiscord Stable
 - Compact Mode enabled? idk
 - Encryption enabled? yes

**Additional context**
Only happens with accounts w/ 2FA

**Comment by l0c4lh057** [comment]
From my support server:

**﻿How to use AccountSwitcher with 2FA﻿**
If you have accounts with 2FA enabled then the token will expire whenever you log out. Just switching accounts does not cause this problem. The last plugin update introduced a new button inside the plugin settings to log out without resetting the token. Simply click that button, log in with your 2FA enabled account again and (remove the account if it already is saved) and then save the account inside the plugin settings.
