### ISSUE TITLE
I cannot Download this, it keeps 408ing me and I cant even download it.

### ISSUE THREAD

**Issue by Mysher2bee** [l0c4lh057/AccountSwitcher#45]
**Additional context**

I cant even download the file itself. It keeps giving me error 408 and saying my browser didnt complete a request in time.

**Comment by Mysher2bee** [comment]
Nvm, i just downloaded the zip instead and took out the file from there. Thats an easy way to just download it.

**Comment by Mysher2bee** [comment]
> 
> 
> how can i download the zip file?

There is a green button like top mid right or so that says 'Code". Click on that and then click "download zip"

**Comment by l0c4lh057** [comment]
Click the following link and then just save with Ctrl+S: https://raw.githubusercontent.com/l0c4lh057/AccountSwitcher/master/AccountSwitcher.plugin.js (jic you didnt get it yet)
