### ISSUE TITLE
[Request] Lightcord Support

### ISSUE THREAD

**Issue by aeoncubed** [l0c4lh057/AccountSwitcher#51]
**Is your feature request related to a problem? Please describe.**
It doesn't show up in the plugin list on Lightcord.

**Describe the solution you'd like**
I'd like to be able to use the plugin in Lightcord.

**Additional context**
Not sure if it's the plugin or Lightcord that makes it unusable.

**Comment by l0c4lh057** [comment]
Don't use Lightshit

**Comment by aeoncubed** [comment]
May I ask why?

**Comment by Juby210** [comment]
Read https://github.com/1Lighty/BetterDiscordPlugins/commit/2309cfb64e2a18669d092af5ca144e7f34dbbdca#commitcomment-44383214
