### ISSUE TITLE
Accountsaving Path

### ISSUE THREAD

**Issue by FeelsBadMan1** [l0c4lh057/AccountSwitcher#52]
Hello,
I try to find the path where the Accountswitcher do save the Tokens but somehow i cant find that file anywhere.....

**Comment by l0c4lh057** [comment]
Inside the BetterDiscord plugins folder there is the AccountSwitcher.plugin.js file, that is the plugin, and the AccountSwitcher.config.json file, that is all the data. No other file is used by the plugin.

**Comment by FeelsBadMan1** [comment]
yes i knew that alredy but the configfle is not there

**Comment by l0c4lh057** [comment]
The file not existing should only be the case if it got deleted or when the plugin did never start yet/settings were never changed so far.

**Comment by FeelsBadMan1** [comment]
well i found it it where in another folder. however the tokens seem to be encrypted. is there a way to decrypt them?

**Comment by l0c4lh057** [comment]
I won't help with encrypting or decrypting tokens.
