### ISSUE TITLE
[Issue] Profile pictures not visible on account switcher.

### ISSUE THREAD

**Issue by wafflethings** [l0c4lh057/AccountSwitcher#54]
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

**Describe the bug**
When middle-clicking on my icon, the account switches shows up and is functional but without profile pictures.

**To Reproduce**
1. Open the account switcher.

**Expected behavior**
The profile pictures to appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/60797216/120772102-d990d780-c517-11eb-9369-2981a9880010.png)
Console logs:
![image](https://user-images.githubusercontent.com/60797216/120772325-1a88ec00-c518-11eb-8153-54ec1f95d052.png)

**Information (please complete the following information):**
 - OS: [Windows]
 - Plugin Version: [1.3.2]
 - Discord version: [Stable]
 - Compact Mode enabled? [no]
 - Encryption enabled? [yes]

**Comment by Carbonixx** [comment]
Can comfirm this is happening to me too
