### ISSUE TITLE
Less of a bug, more of a question

### ISSUE THREAD

**Issue by Serial-Comma** [l0c4lh057/AccountSwitcher#56]
I was wondering where the file containing the tokens was located. I can't find it in the plugins folder, or for that matter any other folder in BetterDiscord. Could you tell me where it is? Thank you.

**Comment by l0c4lh057** [comment]
As already said on discord, they are inside the AccountSwitcher.config.json file inside the BD plugins folder. But since they are encrypted you can't just add/change/read them without knowing how that works. And I won't help with that.
