### ISSUE TITLE
Virustotal "McAfee-GW-Edition" Flags

### ISSUE THREAD

**Issue by ThatBruhMoment** [l0c4lh057/AccountSwitcher#58]
Virustotal.com flags accountswitcher as "BehavesLike.VBS.Dropper.mv" from "McAfee-GW-Edition" and im not sure why it's doing that but it's kinda sketch

**Comment by l0c4lh057** [comment]
oH No, OnE Of 58 AnTiViRuSeS ThInKs tHaT ThErE Is sOmEtHiNg, I DoNt eVeN KnOw wHaT It sAyS BuT THERE IS ONE WHOLE THING DETECTED

**Comment by ThatBruhMoment** [comment]
dick. also one thing is alot, there should be zero if you giving people a program. also just because i dont recognise one string of mother fucking code doesent mean im a dumbass.

**Comment by l0c4lh057** [comment]
> one thing is alot, there should be zero if you giving people a program

I don't give a fuck what some antivirus says, there could be twenty AVs detecting something and it wouldn't change the fact that it is safe. False positives are a thing. Not every negative result means there is nothing malicious and not every positive result means there is something malicious.
And with the "I don't even know what it says" I don't mean you're stupid, I don't know it either. But there is still a huge difference between adware, possibly unwanted behaviour and trojans. Knowing what it detects is a good way to tell whether it actually is something bad or not.
Anyways, read the source code and you'll see exactly what it does. This is one advantage of open source/source available. Or just take a guess if I would be a moderator on the BD server and a verified plugin dev if I distributed malware.
