### ISSUE TITLE
Won't let me configure the settings in the latest version

### ISSUE THREAD

**Issue by Macintosh-Fan** [l0c4lh057/AccountSwitcher#65]
**Describe the bug**
When I want to configure `AccountSwitcher` to add another account, there is no settings option, even with `ZeresPluginLibrary` installed to help this plugin.

**To Reproduce**
1. Install the latest plugin and the needed plugins.

**Expected behavior**
To configure the plugin!

**Screenshots**
![image](https://user-images.githubusercontent.com/50642934/125851094-997a5c77-817a-40b0-be0c-33083d88eb89.png)

**Information (please complete the following information):**
 - OS: macOS Big Sur
 - Plugin Version: Latest
 - Discord version: Stable
 - Compact Mode enabled? No

**Comment by l0c4lh057** [comment]
You first need to enable the plugin, then you can use the settings

**Comment by Macintosh-Fan** [comment]
All good. Thank you.
