### ISSUE TITLE
Crashing better discord

### ISSUE THREAD

**Issue by fco131** [l0c4lh057/AccountSwitcher#66]
**Describe the bug**
It crashes better discord at startup.

**To Reproduce**
1 open disccord
2. wait
3.  better discord crash message

Discord is running on the normal stable version  
windows 10

**Comment by l0c4lh057** [comment]
Please let me know if downloading the latest version of ZLib fixes the issue:
https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js

**Comment by fco131** [comment]
Sorry for responding late I have been  bussy with school But I recently tested  it with the newest version of the plugin library and it seems to work now
