### ISSUE TITLE
[Request] Notifications of all accounts

### ISSUE THREAD

**Issue by ItsdMeSoFYou** [l0c4lh057/AccountSwitcher#73]
Basically I think that it would be great to be able to recieve nofitications from all other accounts in your account switcher. Like I would imagine it like this: You have the red notification thingie on your profile pic and when you do middle mouse button on it to switch accounts, it shows the red thingine on the account you have the notification on.

EDIT: Fixed some Typos

![concept](https://user-images.githubusercontent.com/65194571/142767545-9c1ef5ad-a38c-4470-9271-23fb9ad5f4c6.jpg)
.

**Comment by gunawan817** [comment]
if you change account will you return to the login page? i experienced it

**Comment by ItsdMeSoFYou** [comment]
> if you change account will you return to the login page? i experienced it

No... but tell me, is your comment, even remotely, connected to what I initially wrote?

**Comment by l0c4lh057** [comment]
I have thought about some feature that allows you to use multiple accounts at the same time rather than switching between them, but that is very hard to implement and if fucked up could get your account terminated easily, which is why I decided not to do it.

**Comment by l0c4lh057** [comment]
@gunawan817 if you don't log out in the discord settings but rather with the button in the plugin settings, then it should not be an issue
