### ISSUE TITLE
This Plugin Stole Accounts

### ISSUE THREAD

**Issue by MrMandmal** [l0c4lh057/AccountSwitcher#74]
WHY ?

**Comment by voidfill** [comment]
no :)

**Comment by MrMandmal** [comment]
> no :)

?? 2 of my accounts fucked up

**Comment by voidfill** [comment]
skill issue. 
theres nothing in the plugin that would send your token anywhere, look at the code.

**Comment by iamalicecarroll** [comment]
Can't find any proof to the plugin stealing any tokens, although other apps might be able to steal them if they are not encrypted.
