### ISSUE TITLE
[Request] Add new account using only token

### ISSUE THREAD

**Issue by gorlik1337** [l0c4lh057/AccountSwitcher#9]
I thinking on feature to add bots as usable account. It could be usefull.

**Comment by l0c4lh057** [comment]
I had this as a feature before, but removed it due to possible token abuse. It was not possible to login as a bot with it, I could not get that working with the way BetterDiscord works rn.

**Comment by ShibaeO** [comment]
hi,
but is there a manual way to do it right now ?
